/* Generated by Kodofy by Dark CSS */
(function() {
const initApp = () => {

  // Multi-Page Navigation (client-side routing — all pages in one file)
  function setActiveLink(targetHref) {
     const safeHref = targetHref.replace(/\\/g, '\\\\').replace(/"/g, '\\"').replace(/[\r\n]/g, '');
     document.querySelectorAll('.nav-link-active').forEach(el => el.classList.remove('nav-link-active'));
     document.querySelectorAll(`[data-page-target="${safeHref}"]`).forEach(nl => {
        nl.classList.add('nav-link-active');
        
     });
  }
  
  function navigateTo(hash, updateHistory = false) {
    if (!hash) return;
    let targetId = hash.substring(1);
    let targetPage = document.getElementById(targetId);
    if (!targetPage) { try { targetPage = document.getElementById(decodeURIComponent(targetId)); } catch(e) {} }

    if (targetPage) {
      document.querySelectorAll('.kodofy-page').forEach(p => p.style.display = 'none');
      targetPage.style.display = 'block';
      window.scrollTo({ top: 0, behavior: 'smooth' });
      // Close all drawers
      document.querySelectorAll('.mobile-drawer, #mobile-drawer').forEach(d => {
        d.classList.remove('active', 'open');
      });
      document.querySelectorAll('.mobile-menu-btn').forEach(b => {
        b.innerHTML = '<i class="fa-solid fa-bars"></i>';
      });
      document.querySelectorAll('#site-header').forEach(h => {
        h.classList.remove('blog-menu-open', 'mobile-menu-open');
      });
      document.body.classList.remove('overflow-hidden');
      
      setTimeout(() => { window.dispatchEvent(new Event('resize')); }, 100);
      if (updateHistory) history.pushState(null, '', hash);
      setActiveLink(hash);
      try { localStorage.setItem('kodofy-active-page', hash); } catch(e) {}
    }
  }
  
  window.addEventListener('message', (e) => {
    if (e.data && e.data.type === 'KODOFY_NAVIGATE' && e.data.hash) navigateTo(e.data.hash, false);
  });

  document.addEventListener('click', (e) => {
    const link = e.target.closest('a[href^="#page-"]');
    if (link) {
      const href = link.getAttribute('href');
      if (href !== '#') { e.preventDefault(); navigateTo(href, true); }
    }
  });

  window.addEventListener('popstate', () => {
    let hash = '';
    try { hash = decodeURIComponent(window.location.hash); } catch(e) {}
    if (hash && hash.startsWith('#page-')) navigateTo(hash, false);
    else if (!hash || hash === '#') {
      const pages = document.querySelectorAll('.kodofy-page');
      if (pages.length > 0) {
        pages.forEach(p => p.style.display = 'none');
        pages[0].style.display = 'block';
        window.scrollTo(0, 0);
        const homeId = pages[0].id;
        setActiveLink('#' + homeId);
        try { localStorage.setItem('kodofy-active-page', '#' + homeId); } catch(e) {}
      }
    }
  });


  // Mobile Menu Logic
  document.querySelectorAll('.mobile-menu-btn, .mobile-close-btn').forEach(btn => {
    btn.addEventListener('click', (e) => {
      e.preventDefault();
      const targetId = btn.getAttribute('data-target');
      if (!targetId) return;
      const drawer = document.getElementById(targetId);
      if (!drawer) return;

      const header = btn.closest('header');
      const isBlog = header && header.classList.contains('blog-header-section');
      const isOpen = drawer.classList.contains('active') || drawer.classList.contains('open');

      const closeMenu = () => {
        drawer.classList.remove('active', 'open');
        if (header) header.classList.remove('blog-menu-open', 'mobile-menu-open');
        document.body.classList.remove('overflow-hidden');
        // Find the toggle button for this drawer to reset icon
        const toggler = document.querySelector(`.mobile-menu-btn[data-target="${targetId}"]`);
        if (toggler) toggler.innerHTML = '<i class="fa-solid fa-bars"></i>';
      };

      const openMenu = () => {
        drawer.classList.add(isBlog ? 'active' : 'open');
        if (header) header.classList.add(isBlog ? 'blog-menu-open' : 'mobile-menu-open');
        document.body.classList.add('overflow-hidden');
        btn.innerHTML = '<i class="fa-solid fa-xmark"></i>';
        
        // Handle click outside to close
        const handleOutside = (event) => {
          if (window.__kodofy_toggling) return;
          const path = event.composedPath();
          const isDrawerClick = path.some(el => el === drawer);
          const isBtnClick = path.some(el => el === btn);
          const isToggleClick = path.some(el => el.classList && (el.classList.contains('theme-toggle-btn') || el.classList.contains('search-toggle-btn')));

          if (!isDrawerClick && !isBtnClick && !isToggleClick) {
            closeMenu();
            document.removeEventListener('click', handleOutside);
          }
        };
        setTimeout(() => document.addEventListener('click', handleOutside), 10);
      };

      if (isOpen) closeMenu();
      else openMenu();
    });
  });


  window.addEventListener('resize', () => {
    if (window.innerWidth > 1024) {
      document.querySelectorAll('.mobile-drawer, #mobile-drawer').forEach(drawer => {
        drawer.classList.remove('active', 'open');
      });
      document.querySelectorAll('#site-header').forEach(h => {
        h.classList.remove('blog-menu-open', 'mobile-menu-open');
      });
      document.querySelectorAll('.mobile-menu-btn').forEach(b => {
        b.innerHTML = '<i class="fa-solid fa-bars"></i>';
      });
      document.body.classList.remove('overflow-hidden');
    }
  });


  if (typeof Swiper !== 'undefined' && document.querySelector("#sec-section-7pjlopplx .slider-swiper-section-7pjlopplx")) {
    new Swiper("#sec-section-7pjlopplx .slider-swiper-section-7pjlopplx", {
      slidesPerView: 3, 
      spaceBetween: 30, 
      loop: true, 
      allowTouchMove: false,
      speed: 800,
      watchSlidesProgress: true,
      observer: true,
      observeParents: true,
      navigation: { 
        nextEl: "#sec-section-7pjlopplx .slider-next-section-7pjlopplx", 
        prevEl: "#sec-section-7pjlopplx .slider-prev-section-7pjlopplx" 
      },
      breakpoints: {
        0: { slidesPerView: 1, spaceBetween: 20 },
        768: { slidesPerView: 2, spaceBetween: 24 },
        1024: { slidesPerView: 3, spaceBetween: 30 }
      }
    });
  }



  // Initialize state based on hash
  let initialHash = '';
  try { initialHash = decodeURIComponent(window.location.hash); } catch(e) {}
  if (initialHash && initialHash.startsWith('#page-')) {
    navigateTo(initialHash, false);
  } else {
    let savedPage = null;
    try { savedPage = localStorage.getItem('kodofy-active-page'); } catch(e) {}
    const pages = document.querySelectorAll('.kodofy-page');
    const isExplicitPageSet = pages.length > 0 && pages[0].style.display === 'none';
    if (!isExplicitPageSet && savedPage && savedPage.startsWith('#page-')) {
        let target = document.getElementById(savedPage.substring(1));
        if (!target) { try { target = document.getElementById(decodeURIComponent(savedPage.substring(1))); } catch(e) {} }
        if (target) navigateTo(savedPage, false);
        else { try { localStorage.removeItem('kodofy-active-page'); } catch(e) {} }
    }
  }
};

if (document.readyState === 'loading') {
  document.addEventListener('DOMContentLoaded', initApp);
} else {
  initApp();
}
})();